
<!-- footer -->

<div id="footer">
	<p><small>
		<a href="http://scannerserver.online02.com">$$PROG_NAME</a> 
		<script type="text/javascript">document.write(lang_about.VERSION);</script>$$VER
		<script type="text/javascript">document.write(lang_about.RUNNING_AT);</script>
		<a href="http://$$SERVER_URL">$$SERVER_NAME</a>
		<script type="text/javascript">document.write(lang_about.LANG_LOCALE);</script>
		<script type="text/javascript">document.write(lang_about.TRANSLATED_BY);</script>
		<a id="author_info"></a>
		<script type="text/javascript">
			document.getElementById('author_info').href=lang_about.MAIL_AND_SUBJECT;
			document.getElementById('author_info').innerHTML=lang_about.AUTHOR;
		</script>
	</small></p>
</div>
</div>
</body>
</html>
