<div class="box">
	<h2>$$FILE</h2>
	<p>
		<a href="download.cgi?Scan_$$FILE"><img id="recent_scans_img_download" src="inc/images/download.png" title="$$DOWNLOAD_IMG"></a>
		<a href="print.cgi?Scan_$$FILE" target="_blank"><img id="recent_scans_img_printer" src="inc/images/printer.png" title="$$PRINT_IMG"></a>
		<a href="index.cgi?page=scans&delete=Remove&file=$$FILE"><img id="recent_scans_img_delete" src="inc/images/delete.png" title="$$DELETE_IMG"></a>
		<br />
		<img src="scans/$$IMAGE" width="100%">
	</p>
</div>



